# run-role.yaml

# ex:
# ansible-playbook run-role.yaml -e "topic=mise"
# ansible-playbook run-role.yaml -e "topic=docker"

- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    user_appdir: "{{ lookup('env', 'HOME') }}/Applications"
  tasks:
    - name: "Run topic tasks"
      ansible.builtin.include_tasks:
        file: "apps/{{ topic }}/playbook.yaml"
