#!/usr/bin/env bash
#
# Run all dotfiles installers.
# 
# Original Author: 
# Co-Author:

set -e

cd "$(dirname $0)"/..

echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done