---
# apps/visual-studio-code/tasks/install.yaml

# ── macOS (Homebrew Cask) ─────────────────────────────────────────────────────
- name: "Install visual-studio-code via Homebrew Cask (macOS)"
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
    install_options: "appdir={{ user_appdir }}"
  when: ansible_facts['os_family'] == 'Darwin'
