"""
LLM panel-of-judges evaluation for binned-generated scripts.

Multiple models independently score each generated script on a rubric. The
panel verdict is the mean across all judges. A failing panel mean fails the test.

The default panel uses two local models + one cloud model so evaluation runs
cheaply offline when local inference is available, with a cloud model as a
calibration anchor.

Usage:
    # Default judges (devstral-small-2, qwen3.5, claude-4-sonnet):
    pytest -m llm_judge tests/test_binned_llm_judge.py -v -s

    # Custom generation model and judge panel:
    pytest -m llm_judge tests/test_binned_llm_judge.py -v -s \\
        --gen-model claude-4-sonnet \\
        --judges "devstral-small-2,qwen3.5,claude-4-sonnet,gpt-4.1"

    # Single judge, lower threshold accepted via -k or direct invocation:
    pytest -m llm_judge -k ffmpeg tests/test_binned_llm_judge.py -v -s

Requirements:
    - llm CLI installed and at least one alias configured
    - pip install pytest
"""
from __future__ import annotations

import json
import pathlib
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import NamedTuple

import pytest

pytestmark = pytest.mark.llm_judge

# ── Rubric ────────────────────────────────────────────────────────────────────
#
# structure    — boilerplate present: shebang, set -euo pipefail, die(), usage(),
#                arg parsing with --help / --verbose / --dry-run
# correctness  — does the script implement what the original command does?
# safety       — proper quoting, no unguarded rm -rf, no shell injection risk
# style        — UPPER_SNAKE globals, lower_snake locals, WHY-comments
# completeness — all skeleton placeholders filled in; no stub sections left
#
# verdict: "pass" ≥ 7.0 mean, "needs-work" ≥ 5.0, "fail" < 5.0

_JUDGE_SYSTEM = """\
You are a senior shell-script reviewer assessing a bash script generated by a tool
called `binned`. The tool follows a strict boilerplate template.

Score the script on FIVE criteria (each 0–10). Return ONLY valid JSON — no prose,
no markdown fences — matching this exact schema:

{
  "structure":    <int 0-10>,
  "correctness":  <int 0-10>,
  "safety":       <int 0-10>,
  "style":        <int 0-10>,
  "completeness": <int 0-10>,
  "verdict":      "pass" | "needs-work" | "fail",
  "note":         "<one sentence explaining the biggest strength or weakness>"
}

Scoring rubric:
  structure    10 = has #!/usr/bin/env bash, set -euo pipefail, die(), usage() with
                    --help/-h --verbose/-v --dry-run, argument parser, entry-point block
               5  = most boilerplate present but one section missing or stub
               0  = bare script, no boilerplate
  correctness  10 = fully implements the described command's behaviour
               5  = implements the core action but misses edge cases
               0  = does something unrelated or is broken
  safety       10 = all variables quoted, no injection risk, dangerous ops guarded
               5  = minor quoting gaps on non-user-controlled variables
               0  = obvious injection risk or unguarded destructive operations
  style        10 = UPPER_SNAKE_CASE globals, lower_snake_case locals, comments
                    explain WHY non-obvious things happen (not WHAT)
               5  = naming mostly correct; some what-comments present
               0  = no naming conventions; descriptive comments absent
  completeness 10 = all skeleton placeholders filled; realistic usage examples;
                    dry-run path prints what would happen
               5  = some placeholders remain (e.g. "[add example]")
               0  = majority of body is stubs or TODO comments

verdict:
  "pass"       if mean ≥ 7.0
  "needs-work" if 5.0 ≤ mean < 7.0
  "fail"       if mean < 5.0"""


class JudgeScore(NamedTuple):
    model: str
    structure: int
    correctness: int
    safety: int
    style: int
    completeness: int
    verdict: str
    note: str
    mean: float


def _judge_one(judge_model: str, command: str, script: str) -> JudgeScore:
    prompt = (
        f"Original command the script was generated from:\n\n"
        f"    {command}\n\n"
        f"Generated script:\n\n"
        f"```bash\n{script}\n```\n\n"
        f"Score this script according to the rubric."
    )
    result = subprocess.run(
        ["llm", "-m", judge_model, "--system", _JUDGE_SYSTEM, prompt],
        capture_output=True, text=True, timeout=180,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"llm exited {result.returncode} for judge {judge_model!r}: {result.stderr[:200]}"
        )
    raw = result.stdout.strip()
    # Strip markdown fences if a model ignores the "no fences" instruction
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.MULTILINE)
    raw = re.sub(r"```\s*$", "", raw, flags=re.MULTILINE).strip()
    data = json.loads(raw)
    scores = [data["structure"], data["correctness"], data["safety"],
              data["style"], data["completeness"]]
    return JudgeScore(
        model=judge_model,
        structure=int(data["structure"]),
        correctness=int(data["correctness"]),
        safety=int(data["safety"]),
        style=int(data["style"]),
        completeness=int(data["completeness"]),
        verdict=data["verdict"],
        note=data["note"],
        mean=sum(scores) / len(scores),
    )


def run_panel(command: str, script: str, judge_models: list[str]) -> list[JudgeScore]:
    """Run all judges in parallel; silently drop any that error."""
    scores: list[JudgeScore] = []
    with ThreadPoolExecutor(max_workers=len(judge_models)) as pool:
        futures = {pool.submit(_judge_one, m, command, script): m for m in judge_models}
        for fut in as_completed(futures):
            model = futures[fut]
            try:
                scores.append(fut.result())
            except Exception as exc:
                print(f"\n  [judge {model!r} failed] {exc}", file=sys.stderr)
    return scores


def _print_panel_report(command: str, scores: list[JudgeScore], panel_mean: float,
                         threshold: float) -> None:
    bar = "─" * 64
    print(f"\n{bar}")
    print(f"Command: {command[:70]}{'...' if len(command) > 70 else ''}")
    print(bar)
    for s in scores:
        verdict_icon = {"pass": "✓", "needs-work": "~", "fail": "✗"}.get(s.verdict, "?")
        print(
            f"  {verdict_icon} {s.model:<36s}  mean={s.mean:.1f}"
            f"  [{s.verdict}]"
        )
        print(
            f"    struct={s.structure}  correct={s.correctness}  "
            f"safety={s.safety}  style={s.style}  complete={s.completeness}"
        )
        print(f"    ↳ {s.note}")
    print(bar)
    status = "PASS" if panel_mean >= threshold else "FAIL"
    print(f"  Panel mean: {panel_mean:.2f}  threshold: {threshold}  → {status}")
    print(bar)


# ── Test cases ────────────────────────────────────────────────────────────────
#
# Each entry: (id, command, min_panel_mean)
# min_panel_mean is intentionally modest — we want to catch genuinely bad output,
# not require perfection from every model on every command.

_CASES = [
    (
        "ffmpeg-audio-extract",
        "ffmpeg -i input.mp4 -vn -ar 44100 -ac 2 -b:a 192k output.mp3",
        6.0,
    ),
    (
        "find-delete-old-logs",
        "find . -name '*.log' -mtime +7 -delete",
        6.5,
    ),
    (
        "rsync-backup",
        "rsync -avz --delete ~/Documents/ user@server:/backup/documents/",
        6.0,
    ),
    (
        "git-weekly-count",
        "git log --oneline --since='1 week ago' | wc -l",
        6.5,
    ),
    (
        "curl-jq-pipeline",
        "curl -s https://api.example.com/data | jq '.results[]' | sort -u > out.txt",
        5.5,
    ),
]


@pytest.fixture(scope="session")
def _llm_available():
    if not shutil.which("llm"):
        pytest.skip("llm CLI not found — install with: pip install llm")


@pytest.mark.parametrize("case_id,command,min_mean", _CASES, ids=[c[0] for c in _CASES])
def test_judge_panel(
    case_id, command, min_mean,
    gen_model, judge_models,
    binned_module, _llm_available,
):
    """Generate a script with binned, then score it with a panel of LLM judges."""
    # Generate script
    try:
        script = binned_module.generate_script(
            command, case_id, gen_model, stream=False
        )
    except Exception as exc:
        pytest.skip(f"Script generation failed (model unavailable?): {exc}")

    assert script.strip(), "generate_script returned empty output"

    # Run judge panel
    scores = run_panel(command, script, judge_models)

    if not scores:
        pytest.skip("All judges failed — check that judge model aliases are valid")

    panel_mean = sum(s.mean for s in scores) / len(scores)
    _print_panel_report(command, scores, panel_mean, min_mean)

    assert panel_mean >= min_mean, (
        f"Panel mean {panel_mean:.2f} is below threshold {min_mean} for '{case_id}'.\n"
        f"Judges: {[s.model for s in scores]}\n"
        f"Verdicts: {[(s.model, s.verdict, s.mean) for s in scores]}"
    )


# ── Standalone panel runner (not a pytest test) ───────────────────────────────
# Run directly: uv run --with pytest tests/test_binned_llm_judge.py

if __name__ == "__main__":
    import argparse
    import importlib.machinery
    import importlib.util

    parser = argparse.ArgumentParser(description="Run the binned LLM judge panel standalone")
    parser.add_argument("--gen-model", default=None)
    parser.add_argument("--judges", default="devstral-small-2,qwen3.5,claude-4-sonnet")
    parser.add_argument("command", nargs="?",
                        default="find . -name '*.log' -mtime +7 -delete")
    args = parser.parse_args()

    binned_path = pathlib.Path.home() / "bin" / "binned"
    # binned has no .py extension — use SourceFileLoader so Python treats it as source
    loader = importlib.machinery.SourceFileLoader("binned", str(binned_path))
    spec = importlib.util.spec_from_loader("binned", loader, origin=str(binned_path))
    mod = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    loader.exec_module(mod)

    judges = [m.strip() for m in args.judges.split(",") if m.strip()]
    script = mod.generate_script(args.command, "test-script", args.gen_model, stream=True)
    print("\n" + "─" * 64)
    print("Generated script:")
    print(script)

    scores = run_panel(args.command, script, judges)
    if scores:
        panel_mean = sum(s.mean for s in scores) / len(scores)
        _print_panel_report(args.command, scores, panel_mean, threshold=6.0)
    else:
        print("All judges failed.", file=sys.stderr)
        sys.exit(1)
