[settings]
experimental = true
pipx.uvx = true

[tools]
"cargo:https://github.com/sondr3/git-ignore" = { version = "branch:main", crate = "git-ignore-generator" }
fd = "latest"
fzf = "latest"

# go tooling
go = "latest"

# python tooling
uv = "latest"
python = "latest"
"pipx:pre-commit" = "latest"
"pipx:git-filter-repo" = "latest"
"pipx:gita" = "latest"

# http://llm.datasette.io/en/stable/setup.html
"pipx:llm" = { version = "latest", uvx_args = """
  --with llm-anthropic
  --with llm-gemini
  --with llm-ollama
  --with llm-anthropic
  --with llm-sentence-transformers
  --with llm-tools-exa
  --with llm-pdf-to-images
  --with llm-jq
  --with llm-python
  --with llm-all-models-async
  --with llm-cmd
  --with llm-docs
""" }

# ai tooling
# Aider gets its own isolated venv pinned to 3.12
# mise uses uv tool install under the hood for pipx: backend
# https://aider.chat/docs/install.html
"pipx:aider-chat" = { version = "latest", uvx_args = "--python 3.12 --force" }
prek = "latest"
"pipx:trash-cli" = "latest"
lazygit = "latest"
ansible-core = "latest"
ruby = "latest"
rust = "latest"
"cargo:broot" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fnm" = "latest"
"cargo:goldboot" = "latest"
"cargo:mdcat" = "latest"
"cargo:ripgrep" = "latest"
"cargo:shellharden" = "latest"
"ubi:Canop/broot" = "latest"
"ubi:bootandy/dust" = "latest"
dua = "latest"
duf = "latest"
dust = "latest"
gdu = "latest"
ruff = "latest"
usage = "latest"
"gem:fpm" = "latest"
"pipx:aider-install" = "latest"
"pipx:ansible" = "latest"
"pipx:borgbackup" = "latest"
"pipx:buku" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:copier" = "latest"
"pipx:diceware" = "latest"
"pipx:dinosay" = "latest"
"pipx:editorconfig-checker" = "latest"
"pipx:glances" = "latest"
"pipx:lice" = "latest"
"pipx:magic-wormhole" = "latest"
"pipx:mycroft-mimic3-tts" = "latest"
"pipx:pdm" = "latest"
"pipx:piper-tts" = "latest"
"pipx:podman-compose" = "latest"
"pipx:poetry" = "latest"
"pipx:protonup-ng" = "latest"
"pipx:pyproject-fmt" = "latest"
"pipx:qmk" = "latest"
"pipx:ruff" = "latest"
"pipx:speedtest-cli" = "latest"
"pipx:symbex" = "latest"
"pipx:termdown" = "latest"
"pipx:thefuck" = "latest"
"pipx:tldr" = "latest"
"pipx:toolong" = "latest"
"pipx:watchdog" = "latest"
"pipx:whisperx" = "latest"
"pipx:yt-dlp" = "latest"
"pipx:zxcvbn" = "latest"
